ALTER TABLE devices
ADD COLUMN led_auto_mode BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN buzzer_state BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN relay_state BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE telemetry
ADD COLUMN led_auto_mode BOOLEAN,
ADD COLUMN buzzer_state BOOLEAN,
ADD COLUMN relay_state BOOLEAN;
